#!/bin/sh

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

riverctl spawn 'swaybg -i /home/teapot293/wallp/1.png'
riverctl spawn 'dunst'
riverctl spawn 'systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP'
riverctl spawn '/usr/libexec/polkit-gnome-authentication-agent-1'
riverctl spawn 'dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP'
riverctl spawn 'wl-paste --type text --watch cliphist store'
riverctl spawn 'wl-paste --type image --watch cliphist store'
riverctl spawn 'waybar'
riverctl spawn 'gsettings set org.gnome.desktop.interface gtk-theme Nordic'
riverctl spawn 'gsettings set org.gnome.desktop.interface cursor-size 15'
riverctl spawn 'gsettings set org.gnome.desktop.interface font-name "Fira code medium 11"'
riverctl spawn 'gsettings set org.gnome.desktop.wm.preferences button-layout ""'
# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.

# Super+Shift+Return to start an instance of foot (https://codeberg.org/dnkl/foot)
riverctl map normal Super Return spawn alacritty

riverctl map normal --to-code { 
Super f spawn firefox-wayland
Super e spawn nemo 
Super g spawn geany
Super t spawn telegram-desktop 
Super Q close
Super+Shift E exit
}

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super Right focus-view next
riverctl map normal Super Left focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift Right swap next
riverctl map normal Super+Shift Left swap previous

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Super+Return to bump the focused view to the top of the layout stack
riverctl map normal Super+Shift Return zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super+Control Left send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super+Control Right send-layout-cmd rivertile "main-ratio +0.05"

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+Space to toggle float
riverctl map normal Super Space toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super+Shift F toggle-fullscreen

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'
	
    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 10%+ && /home/teapot293/.config/dunst/scripts/show_volume.sh'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 10%- && /home/teapot293/.config/dunst/scripts/show_volume.sh'
    riverctl map $mode None XF86AudioMute         spawn 'wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && /home/teapot293/.config/dunst/scripts/show_mute.sh'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'
	riverctl map $mode None Print spawn '/home/teapot293/.config/dunst/scripts/screen'

    # Control screen backlight brightness with light (https://github.com/haikarainen/light)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl s +10% && /home/teapot293/.config/dunst/scripts/show_brightness.sh'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl s 10%- && /home/teapot293/.config/dunst/scripts/show_brightness.sh'
done

# Set background and border color
riverctl background-color 0xADD8E6
riverctl border-color-focused 0xADD8E6
riverctl border-color-unfocused 0x586e75
riverctl border-width 3
# Set keyboard repeat rate
riverctl set-repeat 50 300

riverctl float-filter-add app-id float &
riverctl float-filter-add title "popup title with spaces" &

# Set app-ids and titles of views which should use client side decorations
riverctl csd-filter-add app-id "geany"

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -main-ratio 0.5 -view-padding 10 -outer-padding 30 &

### Mouse Stuff ###
# Enable the touchpad config
riverctl input pointer-1739-52632-MSFT0001:00_06CB:CD98_Touchpad events enabled
# Enable natural scrolling
riverctl input pointer-1739-52632-MSFT0001:00_06CB:CD98_Touchpad natural-scroll enabled
# Enable tap to click
riverctl input pointer-1739-52632-MSFT0001:00_06CB:CD98_Touchpad tap enabled
# Enable tap button maps
riverctl input pointer-1739-52632-MSFT0001:00_06CB:CD98_Touchpad tap-button-map left-right-middle 

# Focus follows cursor
riverctl focus-follows-cursor normal

